### ISSUE TITLE
Cubiomes sometimes confuses nether fortresses for bastions and vice versa

### ISSUE THREAD

**Issue by orlp** [Cubitect/cubiomes#62]
Take for example the seed `7324588369055756123`. Opening it in the latest cubiomes-viewer at 1057,736 we predict a bastion and at 1328,656 we predict a fortress. Load up the game and we instead find:

![image](https://user-images.githubusercontent.com/202547/144442063-f53b623d-616c-4144-9bf3-ba19bc49a215.png)

**Comment by Cubitect** [comment]
This was already reported on the cubiomes-viewer issue tracker and should hopefully be fixed now.

**Comment by devjta** [comment]
In which version should this be fixed? Still getting positions of Bastions, instead of fortress.
